version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/app
hooks:
  AfterInstall:
    - location: scripts/strapi/install-deps.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/strapi/start.sh
      timeout: 300
      runas: root
