version: "3.3"
services:
  # yarn service. used for CLI
  yarn:
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: ./dockerfiles/yarn.dockerfile

  client:
    build:
      context: .
      dockerfile: ./dockerfiles/app.dockerfile
    volumes:
      - ./.yarn/cache:/app/.yarn/cache
      - ./apps:/app/apps
      - ./libs:/app/libs
      - ./node_modules:/app/node_modules
      - ./libs/db/node_modules:/app/libs/db/node_modules
    command: yarn nx serve client
    env_file:
      - client.local.env
    ports:
      - "4200:4200"
    depends_on:
      - api
      - strapi

  api:
    build:
      context: .
      dockerfile: ./dockerfiles/app.dockerfile
    volumes:
      - ./.yarn/cache:/app/.yarn/cache
      - ./apps:/app/apps
      - ./libs:/app/libs
      - ./node_modules:/app/node_modules
      - ./libs/db/node_modules:/app/libs/db/node_modules
    command: yarn nx serve api
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://prisma:prisma@api-db:5432/prisma
    ports:
      - "3000:3000"
    depends_on:
      - api-db

  strapi:
    build:
      context: .
      dockerfile: ./dockerfiles/app.dockerfile
    volumes:
      - ./.yarn/cache:/app/.yarn/cache
      - ./apps:/app/apps
      - ./libs:/app/libs
      - ./node_modules:/app/node_modules
      - ./libs/db/node_modules:/app/libs/db/node_modules
      - ./apps/strapi/node_modules:/app/apps/strapi/node_modules
    command: yarn nx serve strapi
    environment:
      - PORT=1337
      - DATABASE_URL=postgresql://prisma:prisma@strapi-db:5432/prisma
    ports:
      - "1337:1337"
    depends_on:
      - strapi-db

  # postgres
  strapi-db:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_DB: prisma
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - /tmp/postgres/starter-project/strapi-db:/var/lib/postgresql/data

  api-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: prisma
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - /tmp/postgres/starter-project/api-db:/var/lib/postgresql/data
