version: "3.3"
services:
  # yarn service. used for CLI
  yarn:
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: ./dockerfiles/yarn.dockerfile

  client:
    build:
      context: .
      dockerfile: ./dockerfiles/app.dockerfile
    volumes:
      - ./.yarn/cache:/app/.yarn/cache
      - ./apps:/app/apps
      - ./libs:/app/libs
    command: yarn nx serve client
    ports:
      - "4200:4200"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: ./dockerfiles/app.dockerfile
    volumes:
      - ./.yarn/cache:/app/.yarn/cache
      - ./apps:/app/apps
      - ./libs:/app/libs
    command: yarn nx serve api
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  # postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: prisma
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - /tmp/postgres/starter-project:/var/lib/postgresql/data
